### PR TITLE
build with and require gegl-0.4

### PR DESCRIPTION
**Pull request by nphilipp**
Fixes: #123 

This is essentially the patch I applied to the Fedora package of libmypaint-1.3.0 (and forgot to submit here, sorry), without generated files.

### CODE REVIEW

**Comment by nphilipp** [comment]
> No code change needed? Cool.

The latest versions of 0.3.x have the same API as 0.4, but won't receive any updates (obviously). :man_shrugging:

**Comment by rezso** [comment]
Latest gegl (0.4.14) contains an API change, so it requires a code change:
https://www.gimpusers.com/forums/gimp-developer/21248-libmypaint-needs-patching-for-recent-gegl

**Comment by kloczek** [comment]
> Latest gegl (0.4.14) contains an API change, so it requires a code change:
> https://www.gimpusers.com/forums/gimp-developer/21248-libmypaint-needs-patching-for-recent-gegl

Yep it fails 

<pre><b>mypaint-gegl-surface.c:</b> In function ‘<b>tile_request_start</b>’:
<b>mypaint-gegl-surface.c:80:40:</b> <font color="#CC0000"><b>error: </b></font>too few arguments to function ‘<b>gegl_buffer_iterator_new</b>’
   80 |         GeglBufferIterator *iterator = <font color="#CC0000"><b>gegl_buffer_iterator_new</b></font>(self-&gt;buffer, &amp;tile_bbox, 0, self-&gt;format,
      |                                        <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~~~~~~~</b></font>
In file included from <b>/usr/include/gegl-0.4/gegl-buffer.h:758</b>,
                 from <b>/usr/include/gegl-0.4/gegl-types.h:96</b>,
                 from <b>/usr/include/gegl-0.4/gegl.h:28</b>,
                 from <b>mypaint-gegl-surface.h:20</b>,
                 from <b>mypaint-gegl-surface.c:22</b>:
<b>/usr/include/gegl-0.4/gegl-buffer-iterator.h:79:22:</b> <font color="#06989A"><b>note: </b></font>declared here
   79 | GeglBufferIterator * <font color="#06989A"><b>gegl_buffer_iterator_new</b></font>  (
      |                      <font color="#06989A"><b>^~~~~~~~~~~~~~~~~~~~~~~~</b></font>
<b>mypaint-gegl-surface.c:91:52:</b> <font color="#CC0000"><b>error: </b></font>‘<b>GeglBufferIterator</b>’ {aka ‘<b>struct GeglBufferIterator</b>’} has no member named ‘<b>data</b>’
   91 |             request-&gt;buffer = (uint16_t *)(iterator<font color="#CC0000"><b>-&gt;</b></font>data[0]);
      |                                                    <font color="#CC0000"><b>^~</b></font>
</pre>

**Comment by Jehan** [comment]
@nphilipp Sorry for not having reviewed this earlier. Would you mind fixing the patch, accounting for GEGL API changes? Should be quite easy to update.

Sorry for not having reviewed this earlier. I'll try and review/merge this as soon as the branch is updated. Thanks!

**Comment by rezso** [comment]
Updated version with gegl 0.4.14 support: https://github.com/mypaint/libmypaint/pull/142

**Comment by jplloyd** [comment]
gegl-0.4 support added: 059e1993d472a578f2f90e4da906003a636549d4
Thank you!
